public class AccountHandlerAssn {
    
    public static void Triggerassnhand1(list<Account>lstAccb){
        TriggerhelperAccount.TriggerAssn(lstAccb);
    }
    public static void Triggeraassnhand2(list<Account>newAcb){
        TriggerhelperAccount.Triggerassn9(newAcb);
    }
    //public static void Triggerassnhand18(list<Account>newLstAcc , map<Id,Account>newMapacc){
        //TriggerhelperAccount.TriggerHelper18(newLstAcc,newMapacc);
   // }

}