public class caseHandler {
    
    public static void AssHandler2(list<Case> newLstc){
        CaseHelper.Trigassn2(newLstc);
        
    }
    
    public static void AssHandler11(list<Case> newLstca){
        CaseHelper.TriggAssn11(newlstca);
        
    }
    
    public static void AssHandler14(list<Case> newLstcas){
        CaseHelper.TriggAssn14(newLstcas);
        
    }
    public static void AssHandler15(list<Case> newLstcase){
        CaseHelper.TriggAssn15(newlstcase);
        
    }
    

    
    
    
    
}