public class OpportunityHandler {
    public Static Void OpportunityHand4(list<Opportunity>newLstOppor){
        OpportunityHelper.Trigassner4(newLstOppor);
    }
    public Static Void OpportunityHand8(list<Opportunity>newLstOpportu){
        OpportunityHelper.Trigassner8(newLstOpportu);
        
    }
    public Static Void OpportunityHand12(list<Opportunity>newLstOpportuni){
        OpportunityHelper.Trigassner12(newLstOpportuni);
    }
    
    public Static Void OpportunityHand13(list<Opportunity>newLstOpportuniy){
        OpportunityHelper.Trigassner13(newLstOpportuniy);
    }
    
    
    
    
}