public class Setall {
    public static void setme(){
        Set<Integer> nest = new Set<Integer>();
        nest.add(1);
        nest.add(2);
        nest.add(3);
        nest.add(4);
        
        System.debug(nest);
    
        Set<Integer> nrt = new set<Integer>{1,2,3,4,5,6};
            System.debug(nrt);
        Set<Integer> neq = new Set<integer>(nrt);
            System.debug(neq);
        List<Integer> qw = new List<Integer>{1,2,1,3,4,3};
            System.debug(qw);
        Set<Integer> re = new Set<Integer>(qw);
            System.debug(re);
        
}
}